# Generated by Django 4.0.4 on 2022-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=255)),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('tipo_canopia', models.CharField(max_length=255)),
                ('forma', models.CharField(max_length=255)),
                ('altura', models.FloatField()),
            ],
            options={
                'verbose_name': 'Arboles',
                'verbose_name_plural': 'Arboles',
            },
        ),
        migrations.CreateModel(
            name='Arbustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=255)),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('tipo_canopia', models.CharField(max_length=255)),
                ('forma', models.CharField(max_length=255)),
                ('altura', models.FloatField()),
            ],
            options={
                'verbose_name': 'Arbustos',
                'verbose_name_plural': 'Arbustos',
            },
        ),
        migrations.CreateModel(
            name='Herbaceas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=255)),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('tipo_canopia', models.CharField(max_length=255)),
                ('forma', models.CharField(max_length=255)),
                ('altura', models.FloatField()),
            ],
            options={
                'verbose_name': 'Herbaceas',
                'verbose_name_plural': 'Herbaceas',
            },
        ),
        migrations.CreateModel(
            name='Semillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=255)),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField()),
            ],
            options={
                'verbose_name': 'Semillas',
                'verbose_name_plural': 'Semillas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=255)),
                ('provincia', models.TextField()),
                ('ciudad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
