# Generated by Django 4.0.4 on 2022-05-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbustos',
            old_name='altura',
            new_name='altura_media_en_metros',
        ),
    ]
